version: '3.1'
services:
  smtp4dev:
    container_name: smtp4dev_container
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '9081:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '9025:25'
     